C PROGRAMA SENCILLO PARA PROBAR EL COMPILADOR
C
C REALIZA ALGO DE LECTURA Y ESCRITURA
C CONTIENE: IF
C CONTIENE: DO
C 
C CONSTRUYE UNA TABLA DE POSICIONES (ENTRE -5 Y 5) Y VALORES DE DOS FUNCIONES.
C CALCULA LA SUMA DE LOS VALORES DE LA FUNCION
C
C  LAS FUNCIONES SON SIN(X), EXP(-|X|) * COS(X)
C
C BJD SEP 2015
C
C LAST MODIFIED: 21 SEP 2015
C
      IMPLICIT NONE

C NUMERO DE POSICIONES
      INTEGER NDIM   
      PARAMETER (NDIM=100)

      REAL XX(NDIM),FUNCI(NDIM),SUMA
      INTEGER IOPT,ERR,IESTADO
      INTEGER I

C INICIALIZA IOPT, SERVIRA PARA ESCOGER
      IOPT=0

 10   WRITE(*,*) 'QUE FUNCION QUIERES ESCRIBIR: 
     1 (1) SIN(X), (2) EXP(-X)*SIN(X)'
      READ(*,*,ERR=20,IOSTAT=IESTADO) IOPT

 20   IF ((IESTADO.NE.0).OR.(IOPT.NE.1.AND.IOPT.NE.2)) THEN 
         WRITE(*,*) 'OPCION INCORRECTA, ESCRIBA 1 o 2'
         GOTO 10
      ENDIF

C CALCULA LOS VALORES DE LA FUNCION

      DO I=1,NDIM
C POSICIONES DE -5 A 5, CON PASO CONSTANTE
         XX(I) = -5. + REAL(I)/NDIM*10.

         IF (IOPT.EQ.1) THEN 
            FUNCI(I) = SIN(XX(I))
         ELSE
            FUNCI(I)=EXP(-ABS(XX(I)))*SIN(XX(I))
         ENDIF

       ENDDO

C CALCULA LA SUMA DE LOS VALORES DE LA FUNCION
       SUMA=0.
       DO I=1,NDIM
          SUMA=SUMA+FUNCI(I)
       ENDDO

C ESCRIBE LOS DATOS EN UN FICHERO
       OPEN(14,FILE='salida.dat')
       DO I=1,NDIM
          WRITE(14,100) XX(I),FUNCI(I)
 100      FORMAT(F9.3,2X,F12.6) 
       ENDDO
       CLOSE(14)

C ESCRIBE EL VALOR DE LA SUMA EN PANTALLA
       WRITE(*,*) ' LA SUMA VALE ',SUMA
       WRITE(*,*) ' POR QUE NO VALE ZERO LA SUMA?'
       END
